site_name: Pang Homepage
site_url: https://jeongsoo-dev.github.io/Pang-Homepage/

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.top
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/Jeongsoo-dev/Pang-Homepage

nav:
  - Home: index.md
  - Blog: blog/index.md
  - About: about.md

extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/extra.js

plugins:
  - search

  # Material built-in blog plugin
  - blog:
      blog_dir: blog
      post_dir: blog/posts
      post_url_format: "{date}/{slug}"
      post_excerpt: optional
      post_excerpt_max_length: 140
      archive: true
      pagination: true
      pagination_per_page: 10

  - git-revision-date-localized:
      enable_creation_date: true
      type: date
