backend:
  name: github
  repo: Jeongsoo-dev/Pang-Homepage
  branch: main
  base_url: https://panghomepage.pages.dev
  auth_endpoint: /api/auth

media_folder: "docs/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "docs/blog/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime", format: "YYYY-MM-DD" }
      - { name: "description", label: "Description", widget: "string", required: false }
      - { name: "body", label: "Body", widget: "markdown" }
